version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.14
    steps:
      - checkout
      - run:
          name: Terraform init
          command: terraform init
      - run:
          name: Touch me
          command: touch thesunalwaysshineon.tv
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Show me
          command: ls -lah
      - run:
          name: Triggertest
          command: echo trigger me
      - run:
          name: Plan
          command: terraform plan
